# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='user',
        ),
    ]
