# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.CharField(default='11/11/1997', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('fb', models.CharField(max_length=50)),
                ('git', models.CharField(max_length=50)),
                ('red', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
